# Generated by Django 5.0.1 on 2024-01-21 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForgetPassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forget_email', models.CharField(max_length=200)),
                ('generated_otp', models.CharField(max_length=200)),
                ('generated_datetime', models.DateTimeField()),
                ('user_otp', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
