# Generated by Django 5.0.1 on 2024-01-21 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_forgetpassword'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forgetpassword',
            name='user_otp',
        ),
    ]
